export const CHANGE_STYLE = 'CHANGE_STYLE';
export const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE';
export const CHANGE_STYLE_PANEL_STATE = 'CHANGE_STYLE_PANEL_STATE';
export const SAVE_CHOOSE_TEMPLATE_CHANGES = 'SAVE_CHOOSE_TEMPLATE_CHANGES';
export const SAVE_MONGODB_STYLE_ID = 'SAVE_MONGODB_STYLE_ID';
export const GET_PROJECT_DATA = 'GET_PROJECT_DATA';

